// demos/react-ui/next-app/pages/_app.tsx
'use client';
import '../styles/globals.css';
import type { AppProps } from 'next/app';
import type { Adapter, WalletError } from '@tronweb3/tronwallet-abstract-adapter';
import { WalletDisconnectedError, WalletNotFoundError } from '@tronweb3/tronwallet-abstract-adapter';
// @ts-ignore
import { toast } from 'react-hot-toast';
import { useEffect, useMemo, useState } from 'react';
import { WalletProvider } from '@tronweb3/tronwallet-adapter-react-hooks';
import { WalletModalProvider } from '@tronweb3/tronwallet-adapter-react-ui';
import '@tronweb3/tronwallet-adapter-react-ui/style.css';
import { LedgerAdapter } from '@tronweb3/tronwallet-adapters';
export default function App({ Component, pageProps }: AppProps) {
    function onError(e: WalletError) {
        if (e instanceof WalletNotFoundError) {
            toast.error(e.message);
        } else if (e instanceof WalletDisconnectedError) {
            toast.error(e.message);
        } else toast.error(e.message);
    }
    const [adapters, setAdapters] = useState<Adapter[]>([]);
    useEffect(() => {
        import('@tronweb3/tronwallet-adapters').then((res) => {
            const {
                BitKeepAdapter,
                OkxWalletAdapter,
                TokenPocketAdapter,
                TronLinkAdapter,
                WalletConnectAdapter,
                SafepalAdapter,
            } = res;
            const tronLinkAdapter = new TronLinkAdapter();
            const ledger = new LedgerAdapter({
                accountNumber: 2,
            });
            const walletConnectAdapter = new WalletConnectAdapter({
                network: 'Nile',
                options: {
                    relayUrl: 'wss://relay.walletconnect.com',
                    // example WC app project ID
                    projectId: '',
                    metadata: {
                        name: 'Test DApp',
                        description: 'Test dApp',
                        url: 'https://your-dapp-url.org/',
                        icons: ['https://your-dapp-url.org/mainLogo.svg'],
                    },
                },
                web3ModalConfig: {
                    themeMode: 'dark',
                    themeVariables: {
                        '--wcm-z-index': '1000',
                    },
                },
            });
            const bitKeepAdapter = new BitKeepAdapter();
            const tokenPocketAdapter = new TokenPocketAdapter();
            const okxwalletAdapter = new OkxWalletAdapter();
            const safepalAdapter = new SafepalAdapter();
            setAdapters([
                tronLinkAdapter,
                bitKeepAdapter,
                tokenPocketAdapter,
                okxwalletAdapter,
                walletConnectAdapter,
                ledger,
                safepalAdapter,
            ]);
        });
    }, [setAdapters]);

    /**
     * wrap your app content with WalletProvider and WalletModalProvider
     * WalletProvider provide some useful properties and methods
     * WalletModalProvider provide a Modal in which you can select wallet you want use.
     *
     * Also you can provide a onError callback to process any error such as ConnectionError
     */
    return (
        <WalletProvider onError={onError} adapters={adapters} disableAutoConnectOnLoad={true}>
            <WalletModalProvider>
                <Component {...pageProps} />
            </WalletModalProvider>
        </WalletProvider>
    );
}

// demos/vue-ui/vite-app/src/App.vue
<script setup lang="ts">
import VueUiDemo from './components/VueUiDemo.vue';
import HooksDemo from './components/HooksDemo.vue';
import { WalletProvider } from '@tronweb3/tronwallet-adapter-vue-hooks';
import { Adapter } from '@tronweb3/tronwallet-abstract-adapter';
import {
    BitKeepAdapter,
    LedgerAdapter,
    OkxWalletAdapter,
    TokenPocketAdapter,
    TronLinkAdapter,
    WalletConnectAdapter,
    BybitWalletAdapter,
    SafepalAdapter
} from '@tronweb3/tronwallet-adapters';
import { WalletModalProvider } from '@tronweb3/tronwallet-adapter-vue-ui';
const tronLink = new TronLinkAdapter();
const walletConnect = new WalletConnectAdapter({
    network: 'Nile',
    options: {
        relayUrl: 'wss://relay.walletconnect.com',
        // example WC app project ID
        projectId: '',
        metadata: {
            name: 'Test DApp',
            description: 'Test dApp',
            url: 'https://your-dapp-url.org/',
            icons: ['https://your-dapp-url.org/mainLogo.svg'],
        },
    },
    web3ModalConfig: {
        themeMode: 'dark',
        themeVariables: {
            '--wcm-z-index': '1000',
        },
        // explorerRecommendedWalletIds: 'NONE',
        enableExplorer: true,
        explorerRecommendedWalletIds: [
            '225affb176778569276e484e1b92637ad061b01e13a048b35a9d280c3b58970f',
            '1ae92b26df02f0abca6304df07debccd18262fdf5fe82daa81593582dac9a369',
            '4622a2b2d6af1c9844944291e5e7351a6aa24cd7b23099efac1b2fd875da31a0',
        ],
        // mobileWallets: [],
        // desktopWallets: []
        // explorerExcludedWalletIds: [
        //   '2c81da3add65899baeac53758a07e652eea46dbb5195b8074772c62a77bbf568'
        // ]
    },
});
const ledger = new LedgerAdapter({
    accountNumber: 2,
});
const tokenPocket = new TokenPocketAdapter();
const bitKeep = new BitKeepAdapter();
const okxWalletAdapter = new OkxWalletAdapter();
const bybit = new BybitWalletAdapter();
const safepal = new SafepalAdapter();
const adapters = [tronLink, walletConnect, ledger, tokenPocket, bitKeep, okxWalletAdapter, bybit, safepal];

function onAdapterChanged(adapter: Adapter) {
    console.log('[wallet hooks] onAdapterChanged: ', adapter?.name);
}
function onReadyStateChanged(readyState: ReadyState) {
    console.log('[wallet hooks] onReadyStateChanged: ', readyState);
}
function onConnect(address: string) {
    console.log('[wallet hooks] onConnect: ', address);
}
function onDisconnect() {
    console.log('[wallet hooks] onDisconnect');
}
function onAccountsChanged(account: string) {
    console.log('[wallet hooks] onAccountsChanged: ', account);
}
function onChainChanged(chainInfo: any) {
    console.log('[wallet hooks] onChainChanged: ', chainInfo);
}
</script>

<template>
    <WalletProvider
        :adapters="adapters"
        @adapter-changed="onAdapterChanged"
        @ready-state-changed="onReadyStateChanged"
        @connect="onConnect"
        @disconnect="onDisconnect"
        @chain-changed="onChainChanged"
        @accounts-changed="onAccountsChanged"
    >
        <WalletModalProvider>
            <VueUiDemo />
            <HooksDemo></HooksDemo>
        </WalletModalProvider>
    </WalletProvider>
</template>

<style scoped>
.logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
}
.logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
    filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
