// packages/react/react-ui/src/Modal/WalletSelectModal.tsx
import { useWallet } from '@tronweb3/tronwallet-adapter-react-hooks';
import type { Wallet } from '@tronweb3/tronwallet-adapter-react-hooks';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { FC, PropsWithChildren } from 'react';
import { AdapterState } from '@tronweb3/tronwallet-abstract-adapter';
import { ReactPortal } from './ReactPortal.js';
import { WalletItem } from '../WalletItem.js';

type ModalProps = PropsWithChildren<{
    visible: boolean;
    onClose: () => void;
}>;
export const WalletSelectModal: FC<ModalProps> = function ({ visible, onClose }) {
    const nodeRef = useRef(null);
    const { wallets, select } = useWallet();
    const [fadeIn, setFadeIn] = useState(false);
    const [render, setRender] = useState(false);

    const walletsList = useMemo(
        () => [
            ...wallets.filter((a: any) => a.state !== AdapterState.NotFound),
            ...wallets.filter((a: any) => a.state === AdapterState.NotFound),
        ],
        [wallets]
    );

    const onWalletClick = useCallback(
        (wallet: Wallet) => {
            select(wallet.adapter.name);
            onClose();
        },
        [select, onClose]
    );
    // The unmount is delayed so the fade-out can play. Clearing the timer on cleanup matters:
    // it runs both before the next effect and on unmount, so reopening within those 200ms
    // cancels the pending `setRender(false)` instead of letting it hide the reopened modal.
    useEffect(
        function () {
            if (visible) {
                setRender(true);
                setFadeIn(true);
                return;
            }

            setFadeIn(false);
            const timer = setTimeout(() => setRender(false), 200);
            return () => clearTimeout(timer);
        },
        [visible]
    );
    useEffect(() => {
        const closeOnEscapeKey = (e: any) => (e.key === 'Escape' ? onClose() : null);
        document.body.addEventListener('keydown', closeOnEscapeKey);
        return () => {
            document.body.removeEventListener('keydown', closeOnEscapeKey);
        };
    }, [onClose]);

    return render ? (
        <ReactPortal wrapperId="react-portal-modal-container">
            <div
                data-testid="wallet-select-modal"
                ref={nodeRef}
                className={`adapter-modal${fadeIn ? ' adapter-modal-fade-in' : ''}`}
            >
                <div className="adapter-modal-wrapper">
                    <div className="adapter-modal-header">
                        <button onClick={onClose} className="close-button" tabIndex={0}></button>
                        <div className="adapter-modal-title">
                            Connect a wallet on
                            <br />
                            Tron to continue
                        </div>
                    </div>

                    <div className="adapter-list">
                        {walletsList.map((wallet) => (
                            <WalletItem
                                key={wallet.adapter.name}
                                wallet={wallet}
                                onClick={() => onWalletClick(wallet)}
                            ></WalletItem>
                        ))}
                    </div>
                </div>
            </div>
        </ReactPortal>
    ) : null;
};

// packages/vue/vue-ui/src/Modal/WalletSelectModal.tsx
import { useWallet } from '@tronweb3/tronwallet-adapter-vue-hooks';
import type { Wallet } from '@tronweb3/tronwallet-adapter-vue-hooks';
import { AdapterState } from '@tronweb3/tronwallet-abstract-adapter';
import { VuePortal } from './VuePortal.js';
import { WalletItem } from '../WalletItem.js';
import { computed, defineComponent, onBeforeMount, onMounted, onUnmounted, ref } from 'vue';
import { createWrapperAndAppendToBody } from '../utils.js';

export const WalletSelectModal = defineComponent({
    props: {
        visible: {
            type: Boolean,
            default: false,
        },
    },
    emits: ['close'],
    setup(props, { emit }) {
        const wrapperId = 'vue-portal-modal-container';
        let element: HTMLDivElement | null;
        let systemCreated = false;
        const { wallets, select } = useWallet();
        const walletsList = computed(() => [
            ...wallets.value.filter((a: any) => a.state !== AdapterState.NotFound),
            ...wallets.value.filter((a: any) => a.state === AdapterState.NotFound),
        ]);

        const closeOnEscapeKey = (e: any) => (e.key === 'Escape' ? emit('close') : null);

        onBeforeMount(() => {
            element = document.querySelector(`#${wrapperId}`);
            if (!element) {
                element = createWrapperAndAppendToBody(wrapperId);
                systemCreated = true;
            }
        });
        onMounted(() => {
            document.body.addEventListener('keydown', closeOnEscapeKey);
        });
        onUnmounted(() => {
            document.body.removeEventListener('keydown', closeOnEscapeKey);
            if (element && systemCreated) {
                document.body.removeChild(element);
            }
        });

        const onWalletClick = (wallet: Wallet) => {
            select(wallet.adapter.name);
            emit('close');
        };

        return () => (
            <VuePortal wrapperId={wrapperId}>
                <div
                    data-testid="wallet-select-modal"
                    class={['adapter-modal', props.visible && 'adapter-modal-fade-in']}
                >
                    <div class="adapter-modal-wrapper">
                        <div class="adapter-modal-header">
                            <button onClick={() => emit('close')} class="close-button" tabindex={0}></button>
                            <div class="adapter-modal-title">
                                Connect a wallet on
                                <br />
                                Tron to continue
                            </div>
                        </div>

                        <div class="adapter-list">
                            {walletsList.value.map((wallet) => (
                                <WalletItem
                                    key={wallet.adapter.name}
                                    wallet={wallet}
                                    onClick={() => {
                                        onWalletClick(wallet);
                                    }}
                                ></WalletItem>
                            ))}
                        </div>
                    </div>
                </div>
            </VuePortal>
        );
    },
});
